### PR TITLE
Provide Nuget Package for Visual Studio on Windows

### PR DESCRIPTION
**Pull request by NaxAlpha**
Hi,
We need nuget package of armadillo for mlpack. I have created nuget for testing but will delete it as soon as official nuget package is ready.

My package link is: https://ci.appveyor.com/project/NaxAlpha/armadillo-code

Thanks

Reference:
https://github.com/mlpack/mlpack/issues/919

### CODE REVIEW

**Comment by rcurtin** [comment]
Hi @NaxAlpha, wouldn't it be more appropriate to simply upload this package to Nuget? I don't think that there is a good reason to put this code in the upstream Armadillo repository.

**Comment by NaxAlpha** [comment]
Yes it is possible to manually build package and upload it on nuget. Yes that would be more appropriate!

**Comment by conradsnicta** [comment]
I would not have accepted this pull request. It contains many problems:
- hardcoded paths
- hardcoded versions of the compiler and OpenBLAS; what happens when people update their compiler or their version of OpenBLAS?
- currently there is no armadillo 7.900; the official releases are at http://arma.sourceforge.net/download.html
- the pull request references an outdated version of OpenBLAS (0.2.14), which is full of bugs

**Comment by NaxAlpha** [comment]
Hi @conradsnicta,

Thanks for feedback. I will try to improve code/commit quality next time and avoid these problems. 

Thanks.

**Comment by conradsnicta** [comment]
@NaxAlpha - It seems you've made NuGet packages for "7.900.0" and "7.900.1".  Please remove them, as there is currently no such thing as Armadillo 7.900.
https://www.nuget.org/packages/armadillo-code/7.900.1
https://www.nuget.org/packages/armadillo-code/7.900.0

Armadillo 7.900 will be eventually released (maybe in 3 months), but it will have significant changes to what you've packaged. This will needlessly confuse people. What made you make the 7.900 package in the first place?

**Comment by NaxAlpha** [comment]
Yes, I am going to do it ASAP. That was a typo

**Pull request closed without merging**
