### PR TITLE
Sparse matrix tests from 2011 to 2017

### PR DESCRIPTION
**Pull request by rcurtin**
This PR has been a long time in the making...

Since I started work on the sparse matrix code in 2011 I (and others who were working with me: @mamidon @jcline (no need for input from you guys, just wanted to let you know this is happening to your work by tagging you)) have kept a suite of tests.  So when I noticed some time back that there was now a test suite as part of the Armadillo repository I decided it was time to update those tests from their original Boost Unit Test Framework formulation into the catch framework (which is pretty nice to work with!).

Unfortunately I could not find the hard drive that contains that repository (it's somewhere in my house... somewhere), so I had to reconstruct these tests from svn diffs from the mailing list of the repository we used to make the sparse code.  That was time consuming and I can't say it was particularly exciting...

I haven't dug too deep back into these tests because I wanted to gauge the reaction of adding them to the Armadillo repository directly first.  Important notes:

 * Sometimes the tests can be pretty extremely exhaustive.  Some may be redundant.
 * My editor kills trailing spaces on lines, so it looks like a decent number of files got caught up in that.  If that's a problem, I can go make those changes reverted.
 * Tests are added not just for sparse matrices, operations, and subviews, but also for HDF5 and a couple other bits of miscellany I've worked on over the years.
 * The tolerances on the random tests are set high enough that they don't break often (if at all).  I ran with ~100+ random seeds and did not see any failures of any tests.

Let me know what you think.  Sorry for the giant and sudden code dump... :)

### CODE REVIEW

**Comment by eddelbuettel** [comment]
Nice.  

@thirdwing also proposed a Google Summer of Code topic on sparse matrix support in RcppArmadillo (and I am trying to help as a backup / 2nd mentor).

**Comment by rcurtin** [comment]
For what it's worth, a project I am finally devoting time to involves replacing the CSC format `sp_mat` with a coordinate list format matrix, because it will probably be significantly faster.  That may, depending on the proposal, slightly affect the work.  (But I also have no idea when I'll be done, just that I am putting a couple hours a week towards it.)

**Comment by conradsnicta** [comment]
Based on a quick look these seem okay.  I'm currently neck deep in Bandicoot development, so I'll take a proper look at these when I have the bandwidth.

**Comment by rcurtin** [comment]
I checked them semi-thoroughly now and pretty thoroughly when originally written, so they shouldn't cause any problems.

**Pull request merged**
