### PR TITLE
Corrected codes for function "hess"

### PR DESCRIPTION
**Pull request by sh-zheng**
Hi~ 
In the corrected codes:
1. All "int" are replaced by "uword" and "blas_int" type convertion is done.
2. Avoid to do operations on "X.get_ref()" and new codes can accept expressions like "A+B".
3. Overflows about "H.n_rows-2" is put into conditional statement to avoid aliasing and a test of square 
    matrix make sure that "H.n_rows=H.n_cols".
4. Empty matrix and 1 by 1 matrix are taken into account respectively.
5. Omissive definition about LAPACK is added.

### CODE REVIEW

**Comment by conradsnicta** [comment]
I'll tentatively merge this into the unstable branch.  The code still has a few minor issues, such as inconsistent indentation and potentially missing handling of a corner case.  I'll fix these over the next few days, so watch for the changes in the unstable branch.  Please study the resultant fixed code before making further contributions.

**Comment by sh-zheng** [comment]
@conradsnicta Thank you for merge them. The code may have some hidden bugs I did not discover. I will try to find them as best as I can. Your coding skills in armadillo are admirable and as a beginner I really want to learn.

**Comment by conradsnicta** [comment]
@sh-zheng - Could you write a few simple tests for hess(), using real and complex matrices?  Something along the lines of checking for non-square matrices, and matrices with n_rows = {0, 1, 2, 4}.  Please see the the `tests` folder: https://github.com/conradsnicta/armadillo-code/tree/unstable/tests

**Comment by sh-zheng** [comment]
@conradsnicta Yes, I will do it.

**Comment by conradsnicta** [comment]
@sh-zheng - Thanks.  Commits: https://github.com/conradsnicta/armadillo-code/commit/c0ca2426bb229a0050c5af655234589b46310c44 https://github.com/conradsnicta/armadillo-code/commit/d400a3c163e1516d2b9e006493e7ce1a5bd0d124

**Pull request merged**
